# Generated by Django 5.1.1 on 2024-09-30 15:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0004_team_is_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_id', models.CharField(editable=False, max_length=100, unique=True)),
                ('midtrans_token', models.CharField(editable=False, max_length=100, unique=True)),
                ('redirect_url', models.URLField(blank=True, editable=False, null=True)),
                ('gross_amount', models.IntegerField()),
                ('payment_status', models.CharField(default='pending', max_length=100)),
                ('fraud_status', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_date', models.DateTimeField(auto_now=True)),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='team.team')),
            ],
        ),
    ]
