# Generated by Django 5.1.1 on 2024-09-21 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_remove_member_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='position',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
