# Generated by Django 5.1.1 on 2024-09-30 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_member_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
