runtime: python310
instance_class: F1
entrypoint: gunicorn -b :$PORT nff.wsgi

env_variables:
  MIDTRANS_SERVER_KEY: SB-Mid-server-z95tREGWWZ7-rFimfPxl-h2z
  MIDTRANS_IS_PRODUCTION: False
  GELOMBANG: ONE

handlers:
- url: /static
  static_dir: static/