POST http://127.0.0.1:8000/auth/login/
Content-Type: application/json

{"username": "hannah", "password": "Pass123!"}

###

POST http://127.0.0.1:8000/auth/signup/
Content-Type: application/json

{"email": "yewwotewwo", "password": "Pass123!"}